server:
  port: 8080

spring:
  datasource:
    # jdbc
    username: epms
    password: epms
    url: jdbc:oracle:thin:@172.16.18.131:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    initialization-mode: never
    schema:
      - classpath*:sql/*.sql
    type: com.alibaba.druid.pool.DruidDataSource
    # jndi
    #jndi-name: java:comp/env/jdbc/epms

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
  config: classpath:logback.xml

#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml,classpath*:mybatis/*Mapper.xml
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: false
  before: true
  enum-as-simple-type: true
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  params: pageNum=current #pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero。
